#!/usr/bin/env snakemake
import sys
import pandas as pd
from pprint import pprint

shell.executable("bash")

configfile: "config.yaml"

include: "rules/kraken2.smk"

rule all:
    input:
        rules.custom_ncbi_refseq_to_kraken2_db.input,
        rules.custom_ncbi_genbank_to_kraken2_db.input,
        rules.ngd_ncbi_refseq_to_kraken2_db.input,
        rules.ngd_ncbi_genbank_to_kraken2_db.input
