#!/usr/bin/env snakemake

import os
import sys
import pandas as pd
import shutil
from pprint import pprint

shell.executable("bash")

configfile: "config.yaml"

include: "rules/kraken2.smk"

rule all:
    input:
        rules.kraken2_16S_gg_db_all.input
